### ISSUE TITLE
请问是只训练了检测机动车辆吗？测试时行人和非机动车辆没有检测到。

### ISSUE THREAD

**Issue by wycrystal** [CAIC-AD/YOLOPv2#10]
请问是只训练了检测机动车辆吗？测试时行人和非机动车辆没有检测到。
![image](https://user-images.githubusercontent.com/81356719/188793459-65382771-cbcc-4d7c-beef-4cee4c3161cb.png)

**Comment by sgzqc** [comment]
你好！感谢你对本项工作的关注，为了和YOLOP做对比，目前只训练了车辆，非机动车和行人未加入训练。同时建议用自动驾驶前向图像做测试，不建议采用监控场景图像做测试。

**Comment by wycrystal** [comment]
自动驾驶前向图像是指相机的成像平面与地面垂直的吗？是不是因为和监控场景角度不一样会导致效果不太好？

**Comment by sgzqc** [comment]
一般来说，我们要求训练集和测试集独立同分布。训练集为自动驾驶场景，测试集尽量也是。  如果你需要应用到监控场景，建议训练集里也加入部分监控场景的图像。

**Comment by wycrystal** [comment]
本质上来讲，是不是还是要摄像头的视角要保持一致？其实我这张测试图片也是车载摄像头拍摄的，现在车子行驶在最右侧车道。

**Comment by sgzqc** [comment]
个人理解换了相机换个视角，模型需要做相应的适配，常用的策略是在原有模型基础上finetune

**Comment by wycrystal** [comment]
感谢回复！
