### ISSUE TITLE
您好，请问是必须有三种任务的标签才可以训练么？

### ISSUE THREAD

**Issue by CC-Xiaoyu** [CAIC-AD/YOLOPv2#12]
只有可行驶区域和车道线的标签可以训练么，比如一张图片上并没有车和人等物体，不需要标注目标检测的标签。

**Comment by sgzqc** [comment]
这个是不需要的，只有可行使域和车道线的，网络里去掉检测的Head即可，损失函数需要相应地去掉检测的Loss

**Comment by CC-Xiaoyu** [comment]
非常感谢，如果在一个数据标签里，图片200张，检测标签有100张，两个分割标签各有200张，这种检测、分割标签数量不对应的情况也可以训练么？因为有的图片只标了分割。

**Comment by sgzqc** [comment]
理论上是可以的 就是在做真值的时候 多传一个1X3的flag 这个flag表示 每个任务是否有真值  比如 111 就表示三个任务都有标注 ； 最后计算loss的时候 根据flag计算相应的loss  只提供简单思路 具体没尝试过
