### ISSUE TITLE
Which backbone of YOLOv7 did you use?

### ISSUE THREAD

**Issue by bigsquirrel18** [CAIC-AD/YOLOPv2#15]
I trained YOLOv7-w6 with BDD100k dataset, but only got 0.807 mAP, and the speed was 62.5 FPS . So I wonder which backbone did you use in the model in order to get such a satisfying score with really impressive speed.

**Comment by CAIC-AD** [comment]
Hello, this work is still under research, and relevant progress is waiting for the company to specify whether to release specific codes. Thank you for your attention! 
Btw, it is worth mentioning that the structure you used is excellent.

**Comment by bigsquirrel18** [comment]
Thank you for reply, I really appreciate it! 

I found that the inference speed was tested in batch size 32 in the paper, and I'm afraid it would be inappropriate to compare it with those tested in batch size 1.

**Comment by CAIC-AD** [comment]
Next, we may consider making a 32 batch size speed comparison.However, at present, we only use 1 batch size for fps testing. 

Btw , I just checked the article and didn't seem to mention it was at 32batch size.

**Comment by bigsquirrel18** [comment]
Oh sorry I've made a mistake, batch size 32 was found from the last line in [https://github.com/CAIC-AD/YOLOPv2/blob/main/data/log/test.log](url) actually. 

Btw, I have tested the model at batch size 1 on my machine, and the inf speed turns out to be 1/0.0163 = 61.34 FPS, slower than that of YOLOP (1/0.0131 = 76.33 FPS) on the same machine. And I also found something weird: when I increase number of running loops from 100 to 1000, the average inference time decreased from 0.0301s to 0.0163s, which I've never met before.

**Comment by CAIC-AD** [comment]
The inf speed is related to the model parameters and memory allocation. Large models may also need to be warmed up in a certain round. You can refer to the inf speed between yolov5s and yolov7 in yolov7's article. 

Btw , on Tesla v100, we tested the inf speed of YOLOP as 0.02~0.024s. We did not measure the time of 0.013s. Thank you for your experiment, which is a very interesting result.
