### ISSUE TITLE
The architecture of backbone

### ISSUE THREAD

**Issue by bigsquirrel18** [CAIC-AD/YOLOPv2#17]
Hi, I printed architecture of the model, and found that the detection part is actually the same as that in [yolov7.yaml](https://github.com/WongKinYiu/yolov7/blob/main/cfg/training/yolov7.yaml) rather than [yolov7-e6e.yaml](https://github.com/WongKinYiu/yolov7/blob/main/cfg/training/yolov7-e6e.yaml). And E-ELAN structure mentioned in the paper isn't the structure used in [yolov7.yaml](https://github.com/WongKinYiu/yolov7/blob/main/cfg/training/yolov7.yaml), but the one used in [yolov7-e6e.yaml](https://github.com/WongKinYiu/yolov7/blob/main/cfg/training/yolov7-e6e.yaml).

Btw, I'm also confused how to generate corresponding segmentation groundtruth if MixUp augmentation is performed in data processing. Since two images are mixed into one, and a pixel can belongs to both of the images. So how to decide which class does a pixel belong to?

**Comment by CAIC-AD** [comment]
Thank you very much for your attention to our work! 

As this work is under study, these specific details are not convenient for discussion now. Please wait for specific follow-up progress and whether the company will release training codes.
