### ISSUE TITLE
分别使用OpenCV、ONNXRuntime部署YOLOPV2目标检测+可驾驶区域分割+车道线分割，一共包含54个onnx模型，依然是包含C++和Python两个版本的程序

### ISSUE THREAD

**Issue by hpc203** [CAIC-AD/YOLOPv2#18]
https://github.com/hpc203/yolopv2-opencv-onnxrun-cpp-py

**Comment by sgzqc** [comment]
Thanks for your attention and we have update the README to aggregation this awesome repositories.
