### ISSUE TITLE
Inference speed slower than results in paper

### ISSUE THREAD

**Issue by BokyLiu** [CAIC-AD/YOLOPv2#22]
I run same video using yolop and yolopv2, using demo.py which from yolop's and yolopv2's repo. The results show inference speed almost as same as each other. The results was tested on Tesla T4, yolop was 36 fps, yolopv2 was 40fps using trace model(faster because trace model?). In your preprint paper, v2 is almost twice faster than yolop.

**Comment by CAIC-AD** [comment]
For our demo version test, the reasoning time of yolop and yolopv2 is 0.020~0.023s, 0.011 and 0.014s respectively in tesla v100. We suggest you try the tesla v100 environment to reproduce the data in the paper (memory allocation is very important for reasoning speed. You can refer to the comparison of reasoning time between yolov5s and yolov7 in yolov7's paper).  In fact, the traced wastes some time but will not appear in offical version.

Btw,You can comment out the 456th line in utils.py,that is helpful for freeing memory.Thank you for your attention.
