### ISSUE TITLE
Drivable area segmentation only

### ISSUE THREAD

**Issue by igormahall** [CAIC-AD/YOLOPv2#23]
Hello.

Is there a way to show the drivable area, but without removing the lane segmentation?

In other words, I want to segment the full road, without treating the drivable and lane segmentations tasks separately.

Attached you can find an example.
![SmartSelect_20220922_081214_Adobe Acrobat.jpg](https://user-images.githubusercontent.com/86990069/191743639-fab69c2d-22b6-4903-bb02-900d847f77b1.jpg)

Thank you very much and congratulations for you great work!

**Comment by sgzqc** [comment]
hi  brother , you can  try this paper's method , visit  this [url](https://arxiv.org/pdf/1805.07029.pdf) .
