### ISSUE TITLE
model has some problem?

### ISSUE THREAD

**Issue by zehranrgi** [CAIC-AD/YOLOPv2#38]
When I searched for (below) this problem, the model seems to have some problems. Has anyone tried using pt model?

I tried at two different machines(also with, CPU and GPU), same issue...

 ```
   161     if isinstance(f, str) or isinstance(f, pathlib.Path):
--> 162         cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
    163     else:
    164         cpp_module = torch._C.import_ir_module_from_buffer(

RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

**Comment by sgzqc** [comment]
Please check this three blogs:
1) [YOLOPv2](https://debuggercafe.com/inference-using-yolopv2-pytorch/)
2) [YOLOP](https://debuggercafe.com/yolop-for-object-detection-and-segmentation/)
3) [HybridNets ](https://debuggercafe.com/running-inference-using-hybridnets-end-to-end-network/)
