### ISSUE TITLE
loss 损失函数设计

### ISSUE THREAD

**Issue by huoguangdiandian** [CAIC-AD/YOLOPv2#6]
文章中提到每个任务都有自己的损失函数，后面又提到dice loss和focal loss，想问一下最后的L=dice loss+focal loss是针对分割任务吗还是整体的损失函数？

**Comment by sgzqc** [comment]
你好！ 感谢你对本工作的关注， L=dice loss+focal loss 主要用于车道线分割任务头。

**Comment by huoguangdiandian** [comment]
好的，多谢回复
