### ISSUE TITLE
感谢开源！请问可开源基于tensorrt部署到nvidia嵌入式设备的代码吗？

### ISSUE THREAD

**Issue by wycrystal** [CAIC-AD/YOLOPv2#9]
如题。

**Comment by sgzqc** [comment]
目前只有Python推理接口，基于后续该项工作进展再考虑是否开发基于Tensorrt的C++推理部分

**Comment by wycrystal** [comment]
谢谢回复！

**Comment by sgzqc** [comment]
你好，这里有个NCNN的 C++ [推理代码](https://github.com/FeiGeChuanShu/YOLOPv2-ncnn)，供参考

**Comment by l-sf** [comment]
你好，我写了YOLOPv2的C++ TensorRT部署代码，并且预处理+后处理解码实现了CUDA核函数，可以参考一下：https://github.com/l-sf/Linfer/blob/main/apps/yolop/yolop.hpp
